version: '3.8'

services:
  growwiz:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GROWWIZ_ENVIRONMENT=PRODUCTION
      - HOST=0.0.0.0
      - PORT=5000
      - SIMULATION_MODE=true
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - growwiz-network

networks:
  growwiz-network:
    driver: bridge